[workspace.package]
version = "1.0.0"
authors = ["Polkadot Fellowship"]
edition = "2021"
repository = "https://github.com/polkadot-fellows/runtimes.git"
license = "GPL-3.0-only"                                        # TODO <https://github.com/polkadot-fellows/runtimes/issues/29>

[workspace.dependencies]
assert_matches = { version = "1.5.0" }
asset-test-utils = { version = "10.0.0" }
assets-common = { version = "0.10.0", default-features = false }
binary-merkle-tree = { version = "15.0.0", default-features = false }
bp-bridge-hub-cumulus = { version = "0.10.0", default-features = false }
bp-header-chain = { version = "0.10.0", default-features = false }
bp-kusama = { version = "0.8.0", default-features = false }
bp-messages = { version = "0.10.0", default-features = false }
bp-parachains = { version = "0.10.0", default-features = false }
bp-polkadot = { version = "0.8.0", default-features = false }
bp-polkadot-core = { version = "0.10.0", default-features = false }
bp-relayers = { version = "0.10.0", default-features = false }
bp-runtime = { version = "0.10.0", default-features = false }
bp-xcm-bridge-hub-router = { version = "0.9.0", default-features = false }
bridge-hub-common = { version = "0.3.0", default-features = false }
bridge-hub-test-utils = { version = "0.10.0" }
bridge-runtime-common = { version = "0.10.0", default-features = false }
clap = { version = "4.5.0" }
cumulus-pallet-aura-ext = { version = "0.10.0", default-features = false }
cumulus-pallet-dmp-queue = { version = "0.10.0", default-features = false }
cumulus-pallet-parachain-system = { version = "0.10.0", default-features = false }
cumulus-pallet-session-benchmarking = { version = "12.0.0", default-features = false }
cumulus-pallet-xcm = { version = "0.10.0", default-features = false }
cumulus-pallet-xcmp-queue = { version = "0.10.0", default-features = false }
cumulus-primitives-aura = { version = "0.10.0", default-features = false }
cumulus-primitives-core = { version = "0.10.0", default-features = false }
cumulus-primitives-utility = { version = "0.10.0", default-features = false }
emulated-integration-tests-common = { version = "6.0.0" }
encointer-balances-tx-payment = { version = "~6.1.0", default-features = false }
encointer-balances-tx-payment-rpc-runtime-api = { version = "~6.1.0", default-features = false }
encointer-primitives = { version = "~6.1.0", default-features = false }
enumflags2 = { version = "0.7.7" }
frame-benchmarking = { version = "31.0.0", default-features = false }
frame-election-provider-support = { version = "31.0.0", default-features = false }
frame-executive = { version = "31.0.0", default-features = false }
frame-remote-externalities = { version = "0.38.0" }
frame-support = { version = "31.0.0", default-features = false }
frame-system = { version = "31.0.0", default-features = false }
frame-system-benchmarking = { version = "31.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "29.0.0", default-features = false }
frame-try-runtime = { version = "0.37.0", default-features = false }
hex-literal = { version = "0.4.1" }
log = { version = "0.4.20", default-features = false }
pallet-alliance = { version = "30.0.0", default-features = false }
pallet-asset-conversion = { version = "13.0.0", default-features = false }
pallet-asset-conversion-tx-payment = { version = "13.0.0", default-features = false }
pallet-asset-rate = { version = "10.0.0", default-features = false }
pallet-asset-tx-payment = { version = "31.0.0", default-features = false }
pallet-assets = { version = "32.0.0", default-features = false }
pallet-aura = { version = "30.0.0", default-features = false }
pallet-authority-discovery = { version = "31.0.1", default-features = false }
pallet-authorship = { version = "31.0.0", default-features = false }
pallet-babe = { version = "31.0.0", default-features = false }
pallet-bags-list = { version = "30.0.0", default-features = false }
pallet-balances = { version = "31.0.0", default-features = false }
pallet-beefy = { version = "31.0.0", default-features = false }
pallet-beefy-mmr = { version = "31.0.0", default-features = false }
pallet-bounties = { version = "30.0.0", default-features = false }
pallet-bridge-grandpa = { version = "0.10.0", default-features = false }
pallet-bridge-messages = { version = "0.10.0", default-features = false }
pallet-bridge-parachains = { version = "0.10.0", default-features = false }
pallet-bridge-relayers = { version = "0.10.0", default-features = false }
pallet-broker = { version = "0.9.0", default-features = false }
pallet-child-bounties = { version = "30.0.0", default-features = false }
pallet-collator-selection = { version = "12.0.0", default-features = false }
pallet-collective = { version = "31.0.0", default-features = false }
pallet-conviction-voting = { version = "31.0.0", default-features = false }
pallet-core-fellowship = { version = "15.0.0", default-features = false }
pallet-election-provider-multi-phase = { version = "30.0.0", default-features = false }
pallet-election-provider-support-benchmarking = { version = "30.0.0", default-features = false }
pallet-encointer-balances = { version = "~6.1.0", default-features = false }
pallet-encointer-bazaar = { version = "~6.1.0", default-features = false }
pallet-encointer-bazaar-rpc-runtime-api = { version = "~6.1.0", default-features = false }
pallet-encointer-ceremonies = { version = "~6.1.0", default-features = false }
pallet-encointer-ceremonies-rpc-runtime-api = { version = "~6.1.0", default-features = false }
pallet-encointer-communities = { version = "~6.1.0", default-features = false }
pallet-encointer-communities-rpc-runtime-api = { version = "~6.1.0", default-features = false }
pallet-encointer-faucet = { version = "~6.1.0", default-features = false }
pallet-encointer-reputation-commitments = { version = "~6.1.0", default-features = false }
pallet-encointer-scheduler = { version = "~6.1.0", default-features = false }
pallet-fast-unstake = { version = "30.0.0", default-features = false }
pallet-glutton = { version = "17.0.0", default-features = false }
pallet-grandpa = { version = "31.0.0", default-features = false }
pallet-identity = { version = "31.0.0", default-features = false }
pallet-indices = { version = "31.0.0", default-features = false }
pallet-insecure-randomness-collective-flip = { version = "19.0.0", default-features = false }
pallet-membership = { version = "31.0.0", default-features = false }
pallet-message-queue = { version = "34.0.0", default-features = false }
pallet-mmr = { version = "30.0.0", default-features = false }
pallet-multisig = { version = "31.0.0", default-features = false }
pallet-nft-fractionalization = { version = "13.0.0", default-features = false }
pallet-nfts = { version = "25.0.0", default-features = false }
pallet-nfts-runtime-api = { version = "17.0.0", default-features = false }
pallet-nis = { version = "31.0.0", default-features = false }
pallet-nomination-pools = { version = "28.0.0", default-features = false }
pallet-nomination-pools-benchmarking = { version = "29.0.0", default-features = false }
pallet-nomination-pools-runtime-api = { version = "26.0.0", default-features = false }
pallet-offences = { version = "30.0.0", default-features = false }
pallet-offences-benchmarking = { version = "31.0.0", default-features = false }
pallet-parameters = { version = "0.2.0", default-features = false }
pallet-preimage = { version = "31.0.0", default-features = false }
pallet-proxy = { version = "31.0.0", default-features = false }
pallet-ranked-collective = { version = "31.0.0", default-features = false }
pallet-recovery = { version = "31.0.0", default-features = false }
pallet-referenda = { version = "31.0.0", default-features = false }
pallet-salary = { version = "16.0.0", default-features = false }
pallet-scheduler = { version = "32.0.0", default-features = false }
pallet-session = { version = "31.0.0", default-features = false }
pallet-session-benchmarking = { version = "31.0.0", default-features = false }
pallet-society = { version = "31.0.0", default-features = false }
pallet-staking = { version = "31.0.0", default-features = false }
pallet-staking-reward-curve = { version = "11.0.0" }
pallet-staking-reward-fn = { version = "21.0.0", default-features = false }
pallet-staking-runtime-api = { version = "17.0.0", default-features = false }
pallet-state-trie-migration = { version = "32.0.0", default-features = false }
pallet-sudo = { version = "31.0.0", default-features = false }
pallet-timestamp = { version = "30.0.0", default-features = false }
pallet-transaction-payment = { version = "31.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "31.0.0", default-features = false }
pallet-treasury = { version = "30.0.0", default-features = false }
pallet-uniques = { version = "31.0.0", default-features = false }
pallet-utility = { version = "31.0.0", default-features = false }
pallet-vesting = { version = "31.0.0", default-features = false }
pallet-whitelist = { version = "30.0.0", default-features = false }
pallet-xcm = { version = "10.0.0", default-features = false }
pallet-xcm-benchmarks = { version = "10.0.0", default-features = false }
pallet-xcm-bridge-hub = { version = "0.5.0", default-features = false }
pallet-xcm-bridge-hub-router = { version = "0.8.0", default-features = false }
parachains-common = { version = "10.0.0", default-features = false }
parachains-runtimes-test-utils = { version = "10.0.0" }
parity-scale-codec = { version = "3.6.9", default-features = false }
paste = { version = "1.0.14" }
penpal-runtime = { version = "0.17.0" }
polkadot-core-primitives = { version = "10.0.0", default-features = false }
polkadot-parachain-primitives = { version = "9.0.0", default-features = false }
polkadot-primitives = { version = "10.0.0", default-features = false }
polkadot-runtime-common = { version = "10.0.0", default-features = false }
polkadot-runtime-parachains = { version = "10.0.0", default-features = false }
primitive-types = { version = "0.12.2", default-features = false }
sc-chain-spec = { version = "30.0.0" }
sc-consensus-grandpa = { version = "0.22.0" }
scale-info = { version = "2.10.0", default-features = false }
separator = { version = "0.4.1" }
serde = { version = "1.0.196" }
serde_json = { version = "1.0.113" }
smallvec = { version = "1.13.1" }
snowbridge-beacon-primitives = { version = "0.3.0", default-features = false }
snowbridge-core = { version = "0.3.0", default-features = false }
snowbridge-outbound-queue-runtime-api = { version = "0.3.0", default-features = false }
snowbridge-pallet-ethereum-client = { version = "0.3.0", default-features = false }
snowbridge-pallet-inbound-queue = { version = "0.3.0", default-features = false }
snowbridge-pallet-inbound-queue-fixtures = { version = "0.11.0" }
snowbridge-pallet-outbound-queue = { version = "0.3.0", default-features = false }
snowbridge-pallet-system = { version = "0.3.0", default-features = false }
snowbridge-router-primitives = { version = "0.9.0", default-features = false }
snowbridge-runtime-common = { version = "0.3.0", default-features = false }
snowbridge-runtime-test-common = { version = "0.3.0" }
snowbridge-system-runtime-api = { version = "0.3.0", default-features = false }
sp-api = { version = "29.0.0", default-features = false }
sp-application-crypto = { version = "33.0.0", default-features = false }
sp-arithmetic = { version = "25.0.0", default-features = false }
sp-authority-discovery = { version = "29.0.0", default-features = false }
sp-block-builder = { version = "29.0.0", default-features = false }
sp-consensus-aura = { version = "0.35.0", default-features = false }
sp-consensus-babe = { version = "0.35.0", default-features = false }
sp-consensus-beefy = { version = "16.0.0", default-features = false }
sp-core = { version = "31.0.0", default-features = false }
sp-debug-derive = { version = "14.0.0", default-features = false }
sp-genesis-builder = { version = "0.10.0", default-features = false }
sp-inherents = { version = "29.0.0", default-features = false }
sp-io = { version = "33.0.0", default-features = false }
sp-keyring = { version = "34.0.0" }
sp-npos-elections = { version = "29.0.0", default-features = false }
sp-offchain = { version = "29.0.0", default-features = false }
sp-runtime = { version = "34.0.0", default-features = false }
sp-session = { version = "30.0.0", default-features = false }
sp-staking = { version = "29.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-storage = { version = "20.0.0", default-features = false }
sp-tracing = { version = "16.0.0", default-features = false }
sp-transaction-pool = { version = "29.0.0", default-features = false }
sp-trie = { version = "32.0.0" }
sp-version = { version = "32.0.0", default-features = false }
sp-weights = { version = "30.0.0", default-features = false }
staging-parachain-info = { version = "0.10.0", default-features = false }
staging-xcm = { version = "10.0.0", default-features = false }
staging-xcm-builder = { version = "10.0.0", default-features = false }
staging-xcm-executor = { version = "10.0.0", default-features = false }
static_assertions = { version = "1.1.0" }
substrate-wasm-builder = { version = "20.0.0" }
tokio = { version = "1.36.0" }
xcm-emulator = { version = "0.8.0" }

[workspace]
resolver = "2"

members = [
	"chain-spec-generator",
	"relay/kusama",
	"relay/kusama/constants",
	"relay/polkadot",
	"relay/polkadot/constants",
	"system-parachains/asset-hubs/asset-hub-kusama",
	"system-parachains/asset-hubs/asset-hub-kusama/primitives",
	"system-parachains/asset-hubs/asset-hub-polkadot",
	"system-parachains/asset-hubs/asset-hub-polkadot/primitives",
	"system-parachains/bridge-hubs/bridge-hub-kusama",
	"system-parachains/bridge-hubs/bridge-hub-kusama/primitives",
	"system-parachains/bridge-hubs/bridge-hub-polkadot",
	"system-parachains/bridge-hubs/bridge-hub-polkadot/primitives",
	"system-parachains/collectives/collectives-polkadot",
	"system-parachains/collectives/collectives-polkadot/constants",
	"system-parachains/constants",
	"system-parachains/coretime/coretime-kusama",
	"system-parachains/encointer",
	"system-parachains/gluttons/glutton-kusama",
	"system-parachains/people/people-kusama",
	"integration-tests/emulated/chains/relays/kusama",
	"integration-tests/emulated/chains/relays/polkadot",
	"integration-tests/emulated/chains/parachains/assets/asset-hub-kusama",
	"integration-tests/emulated/chains/parachains/assets/asset-hub-polkadot",
	"integration-tests/emulated/chains/parachains/bridges/bridge-hub-kusama",
	"integration-tests/emulated/chains/parachains/bridges/bridge-hub-polkadot",
	"integration-tests/emulated/chains/parachains/collectives/collectives-polkadot",
	"integration-tests/emulated/chains/parachains/people/people-kusama",
	"integration-tests/emulated/chains/parachains/testing/penpal",
	"integration-tests/emulated/helpers",
	"integration-tests/emulated/networks/kusama-system",
	"integration-tests/emulated/networks/polkadot-system",
	"integration-tests/emulated/networks/kusama-polkadot-system",
	"integration-tests/emulated/tests/assets/asset-hub-kusama",
	"integration-tests/emulated/tests/assets/asset-hub-polkadot",
	"integration-tests/emulated/tests/bridges/bridge-hub-kusama",
	"integration-tests/emulated/tests/bridges/bridge-hub-polkadot",
	"integration-tests/emulated/tests/collectives/collectives-polkadot",
	"integration-tests/emulated/tests/people/people-kusama",
]

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
